on:
  push:
    branches:
      - gh-pages
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: yarn install
        run: yarn install

      - name: gatsby build
        run: yarn build

      - name: deploy
        uses: maxheld83/ghpages@v0.3.0
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: '.'